// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWUmcORMCrR5JmkfNpQ4BP8NM97fp8epE',
    appId: '1:510663741050:web:0265db6c0a3c3ea44f35c3',
    messagingSenderId: '510663741050',
    projectId: 'cleanmates-ea347',
    authDomain: 'cleanmates-ea347.firebaseapp.com',
    databaseURL: 'https://cleanmates-ea347-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cleanmates-ea347.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs2E5yqo4f8ZqnvNCZRsy9naFExwZK5JM',
    appId: '1:510663741050:android:acf11f59104e13fe4f35c3',
    messagingSenderId: '510663741050',
    projectId: 'cleanmates-ea347',
    databaseURL: 'https://cleanmates-ea347-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cleanmates-ea347.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEdfjUCyPu2WBmScewrXETIrtFKx6zT7w',
    appId: '1:510663741050:ios:0be29e6274326c654f35c3',
    messagingSenderId: '510663741050',
    projectId: 'cleanmates-ea347',
    databaseURL: 'https://cleanmates-ea347-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cleanmates-ea347.appspot.com',
    iosClientId: '510663741050-d2grmg4487aq5bfbevhanpn0f42doajt.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanMatesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEdfjUCyPu2WBmScewrXETIrtFKx6zT7w',
    appId: '1:510663741050:ios:0be29e6274326c654f35c3',
    messagingSenderId: '510663741050',
    projectId: 'cleanmates-ea347',
    databaseURL: 'https://cleanmates-ea347-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cleanmates-ea347.appspot.com',
    iosClientId: '510663741050-d2grmg4487aq5bfbevhanpn0f42doajt.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanMatesApp',
  );
}
